//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_FASSN_reg
    {
        public int ID { get; set; }
        public string SN { get; set; }
        public int LOTID { get; set; }
        public short UserID { get; set; }
        public Nullable<short> AppID { get; set; }
        public byte LineID { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
