//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_PackingTable
    {
        public int ID { get; set; }
        public Nullable<int> PCBID { get; set; }
        public Nullable<int> SNID { get; set; }
        public int LOTID { get; set; }
        public byte LiterID { get; set; }
        public short LiterIndex { get; set; }
        public short PalletNum { get; set; }
        public short BoxNum { get; set; }
        public short UnitNum { get; set; }
        public System.DateTime PackingDate { get; set; }
        public short UserID { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
        public Nullable<short> UpdBy { get; set; }
    }
}
