//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ct_StepResult
    {
        public int PCBID { get; set; }
        public short StepID { get; set; }
        public byte TestResult { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public Nullable<int> SNID { get; set; }
    
        public virtual Ct_StepScan Ct_StepScan { get; set; }
        public virtual Ct_TestResult Ct_TestResult { get; set; }
    }
}
