//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depo_SN_MAC
    {
        public int ID { get; set; }
        public string SN { get; set; }
        public string MAC1 { get; set; }
        public string MAC2 { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> LOTID { get; set; }
        public Nullable<byte> MAC_Count { get; set; }
    }
}
