//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FASEntities : DbContext
    {
        public FASEntities()
            : base("name=FASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract_LOT> Contract_LOT { get; set; }
        public virtual DbSet<Ct_FASSN_reg> Ct_FASSN_reg { get; set; }
        public virtual DbSet<Ct_PackingTable> Ct_PackingTable { get; set; }
        public virtual DbSet<Ct_OperLog> Ct_OperLog { get; set; }
        public virtual DbSet<FAS_Lines> FAS_Lines { get; set; }
        public virtual DbSet<FAS_Liter> FAS_Liter { get; set; }
        public virtual DbSet<FAS_Users> FAS_Users { get; set; }
        public virtual DbSet<Depo_SN_MAC> Depo_SN_MAC { get; set; }
    }
}
