//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Lines
    {
        public byte LineID { get; set; }
        public string LineName { get; set; }
        public byte TipeID { get; set; }
        public string Print_Line { get; set; }
        public Nullable<byte> Flat_LineID { get; set; }
    }
}
