//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SberDevice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAS_Users
    {
        public short UserID { get; set; }
        public string RFID { get; set; }
        public string UserName { get; set; }
        public bool IsActiv { get; set; }
        public byte UsersGroupID { get; set; }
        public Nullable<int> IDService { get; set; }
    }
}
